// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79gemoOUFF7YhvgQ7bKcj4JH4jbIKuPI',
    appId: '1:356656018126:web:2a5e3180705c78c8a7569f',
    messagingSenderId: '356656018126',
    projectId: 'dermassist-7e5da',
    authDomain: 'dermassist-7e5da.firebaseapp.com',
    storageBucket: 'dermassist-7e5da.firebasestorage.app',
    measurementId: 'G-YB6GMSXJR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKkqB_0hrxCxSzNEHVt2I4hGi7CdzByk',
    appId: '1:193796436282:android:7e53b2f3890a855c5fa003',
    messagingSenderId: '193796436282',
    projectId: 'dermassist-d8a65',
    storageBucket: 'dermassist-d8a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAI7Gu9eI-Jc-7n3PHGY-89C0ePU8tWwE',
    appId: '1:356656018126:ios:cd0b512ff23a1367a7569f',
    messagingSenderId: '356656018126',
    projectId: 'dermassist-7e5da',
    storageBucket: 'dermassist-7e5da.firebasestorage.app',
    iosBundleId: 'com.example.dermassistFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAI7Gu9eI-Jc-7n3PHGY-89C0ePU8tWwE',
    appId: '1:356656018126:ios:cd0b512ff23a1367a7569f',
    messagingSenderId: '356656018126',
    projectId: 'dermassist-7e5da',
    storageBucket: 'dermassist-7e5da.firebasestorage.app',
    iosBundleId: 'com.example.dermassistFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC79gemoOUFF7YhvgQ7bKcj4JH4jbIKuPI',
    appId: '1:356656018126:web:e327a089165ed6cca7569f',
    messagingSenderId: '356656018126',
    projectId: 'dermassist-7e5da',
    authDomain: 'dermassist-7e5da.firebaseapp.com',
    storageBucket: 'dermassist-7e5da.firebasestorage.app',
    measurementId: 'G-5L3SGM3QXV',
  );
}